# kubectl apply -f drops-pv.yaml
# kubectl delete -f drops-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: docfxhelper
    tier: publisher
    type: local
  name: drops-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/c/dev/docfxhelper/Drops
    
