# kubectl apply -f publisher-site-pv.yaml
# kubectl delete -f publisher-site-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: docfxhelper
    tier: publisher
    type: local
  name: publisher-site-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/c/dev/docfxhelper/Site
