# kubectl apply -f publisher-svc.yaml
# kubectl delete -f publisher-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docfxhelper
    tier: publisher
  name: publisher-svc
spec:
  ports:
    - name: publisherweb
      port: 8086
      targetPort: 80
  selector:
    app: docfxhelper
    tier: publisher
  type: LoadBalancer