# kubectl apply -f site-site-pv.yaml
# kubectl delete -f site-site-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: docfxhelper
    tier: site
    type: local
  name: site-site-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /run/desktop/mnt/host/c/dev/docfxhelper/Site
