# kubectl apply -f site-deploy.yaml
# kubectl delete -f site-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docfxhelper
    tier: site
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docfxhelper
      tier: site
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: docfxhelper
        tier: site
    spec:
      containers:
        - env:
            - name: NGINX_PORT
              value: "80"
          image: site:local
          name: site
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: site
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      restartPolicy: Always
      volumes:
        - name: site
          persistentVolumeClaim:
            claimName: site-site-pvc
