# kubectl apply -f site-svc.yaml
# kubectl delete -f site-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: docfxhelper
    tier: site
  name: site-svc
spec:
  ports:
    - name: siteweb
      port: 8085
      targetPort: 80
  selector:
    app: docfxhelper
    tier: site
  type: LoadBalancer