# kubectl apply -f workspace-pvc.yaml
# kubectl delete -f workspace-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:    
    app: docfxhelper
    tier: publisher
    type: local
  name: workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: hostpath
  volumeName: workspace-pv