# docker compose --file docker.compose.yml --project-name docfxhelper build
# docker compose --file docker.compose.yml --project-name docfxhelper up
# docker compose --file docker.compose.yml --project-name docfxhelper down
# docker compose --file docker.compose.yml --project-name docfxhelper rm
name: docs
services:
  site:
    build:
      context: .
      dockerfile: docs.dockerfile
    image: docs:local
    ports:
      - "8084:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - site:/usr/share/nginx/html/
  publisher:
    build:
      context: .
      dockerfile: publisher.dockerfile
    image: publisher:local
    volumes:
      - drops:/docfxhelper/drops
      - workspace:/docfxhelper/workspace
      - site:/docfxhelper/site
      - publishersite:/docfxhelper/publishersite
      - publisherlogs:/docfxhelper/publisherlogs
volumes:
  drops:     # docker volume create --opt type=none --opt o=bind --opt device=/mnt/c/dev/docfxhelper/Drops drops
    external: true
    name: drops
  workspace: # docker volume create --opt type=none --opt o=bind --opt device=/mnt/c/dev/docfxhelper/Workspace workspace
    external: true
    name: workspace
  site:      # docker volume create --opt type=none --opt o=bind --opt device=/mnt/c/dev/docfxhelper/Site site
    external: true
    name: site
  publishersite: # docker volume create --opt type=none --opt o=bind --opt device=/mnt/c/dev/docfxhelper/publishersite publishersite
    external: true
    name: publishersite
  publisherlogs: # docker volume create --opt type=none --opt o=bind --opt device=/mnt/c/dev/docfxhelper/publisherlogs publisherlogs
    external: true
    name: publisherlogs