// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using DocFxHelper.Common;
//
//    var docFx = DocFx.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace DocFxHelper.Common
{
  using System;
  using System.Collections.Generic;

  using System.Text.Json;
  using System.Text.Json.Serialization;
  using System.Globalization;

  public partial class DocFx
  {
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("$schema")]
    public string Schema { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("build")]
    public BuildJsonConfig Build { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merge")]
    public MergeElement[] Merge { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("metadata")]
    public MetadatumElement[] Metadata { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rules")]
    public Dictionary<string, RuleValue> Rules { get; set; }
  }

  /// <summary>
  /// Build section defines configuration values for the build command.
  /// </summary>
  public partial class BuildJsonConfig
  {
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("content")]
    public Content? Content { get; set; }

    /// <summary>
    /// Set the name of ICustomHrefGenerator derived class.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customLinkResolver")]
    public string CustomLinkResolver { get; set; }

    /// <summary>
    /// Run in debug mode.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("debug")]
    public bool? Debug { get; set; }

    /// <summary>
    /// The output folder for files generated for debugging purpose when in debug mode.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("debugOutput")]
    public string DebugOutput { get; set; }

    /// <summary>
    /// (Deprecated) Defines the output folder of the generated build files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dest")]
    public string Dest { get; set; }

    /// <summary>
    /// Disable fetching Git related information for articles.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disableGitFeatures")]
    public bool? DisableGitFeatures { get; set; }

    /// <summary>
    /// If set to true, template will not be actually applied to the documents.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dryRun")]
    public bool? DryRun { get; set; }

    /// <summary>
    /// If set to true, data model to run template script will be extracted in .raw.model.json
    /// extension.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("exportRawModel")]
    public bool? ExportRawModel { get; set; }

    /// <summary>
    /// If set to true, data model to apply template will be extracted in .view.model.json
    /// extension.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("exportViewModel")]
    public bool? ExportViewModel { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fileMetadata")]
    public Dictionary<string, object> FileMetadata { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fileMetadataFiles")]
    public Exclude? FileMetadataFiles { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("globalMetadata")]
    public Dictionary<string, object> GlobalMetadata { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("globalMetadataFiles")]
    public Exclude? GlobalMetadataFiles { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("groups")]
    public Dictionary<string, GroupValue> Groups { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("markdownEngineProperties")]
    public MarkdownEngineProperties MarkdownEngineProperties { get; set; }

    /// <summary>
    /// Set the max parallelism, 0 is auto.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("maxParallelism")]
    public long? MaxParallelism { get; set; }

    /// <summary>
    /// Defines the output folder of the generated build files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("output")]
    public string Output { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("overwrite")]
    public Content? Overwrite { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("postProcessors")]
    public Exclude? PostProcessors { get; set; }

    /// <summary>
    /// Specify the output folder for the raw model.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rawModelOutputFolder")]
    public string RawModelOutputFolder { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("resource")]
    public Content? Resource { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("sitemap")]
    public Sitemap Sitemap { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("template")]
    public Exclude? Template { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("theme")]
    public Exclude? Theme { get; set; }

    /// <summary>
    /// Specify the output folder for the view model.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("viewModelOutputFolder")]
    public string ViewModelOutputFolder { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("xref")]
    public Exclude? Xref { get; set; }
  }

  /// <summary>
  /// FileMappingItem
  /// </summary>
  public partial class DocF
  {
    /// <summary>
    /// Pattern match will be case sensitive.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("case")]
    public bool? Case { get; set; }

    /// <summary>
    /// The destination folder for the files if copy/transform is used.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dest")]
    public string Dest { get; set; }

    /// <summary>
    /// Allow files start with `.` to be matched even if `.` is not explicitly specified in the
    /// pattern.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dot")]
    public bool? Dot { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("exclude")]
    public Exclude? Exclude { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("files")]
    public Exclude? Files { get; set; }

    /// <summary>
    /// Group name for the current file-mapping item.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("group")]
    public string Group { get; set; }

    /// <summary>
    /// The name of current item, the value is not used for now
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string Name { get; set; }

    /// <summary>
    /// Disable the usage of `\` to escape values.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("noEscape")]
    public bool? NoEscape { get; set; }

    /// <summary>
    /// Disable `{a,b}c` => `["ac", "bc"]`.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("noExpand")]
    public bool? NoExpand { get; set; }

    /// <summary>
    /// Disable the usage of `**` to match everything including `/` when it is the beginning of
    /// the pattern or is after `/`.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("noGlobStar")]
    public bool? NoGlobStar { get; set; }

    /// <summary>
    /// Disable pattern begin with `!` to mean negate.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("noNegate")]
    public bool? NoNegate { get; set; }

    /// <summary>
    /// The Root TOC Path used for navbar in current group, relative to output root.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rootTocPath")]
    public string RootTocPath { get; set; }

    /// <summary>
    /// `src` defines the root folder for the source files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("src")]
    public string Src { get; set; }
  }

  public partial class GroupValue
  {
    /// <summary>
    /// Defines the output folder of the generated build files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dest")]
    public string Dest { get; set; }
  }

  /// <summary>
  /// Set the parameters for markdown engine, value should be a JSON string.
  /// </summary>
  public partial class MarkdownEngineProperties
  {
    /// <summary>
    /// Alert keywords in markdown without the surrounding [!] and the corresponding CSS class
    /// names.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("alerts")]
    public Dictionary<string, string> Alerts { get; set; }

    /// <summary>
    /// Enables line numbers
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("enableSourceInfo")]
    public bool? EnableSourceInfo { get; set; }

    /// <summary>
    /// Fallback folders
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fallbackFolders")]
    public string[] FallbackFolders { get; set; }

    /// <summary>
    /// List of optional Markdig extensions to add or modify settings.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("markdigExtensions")]
    public MarkdigExtensionElement[] MarkdigExtensions { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("plantUml")]
    public PlantUml PlantUml { get; set; }
  }

  public partial class MarkdigExtensionClass
  {
    /// <summary>
    /// markdig extension name
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string Name { get; set; }
  }

  /// <summary>
  /// PlantUml extension configuration parameters
  /// </summary>
  public partial class PlantUml
  {
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("delimitor")]
    public string Delimitor { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("javaPath")]
    public string JavaPath { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("localGraphvizDotPath")]
    public string LocalGraphvizDotPath { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("localPlantUmlPath")]
    public string LocalPlantUmlPath { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("outputFormat")]
    public PlantUmlOutputFormat? OutputFormat { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("remoteUrl")]
    public string RemoteUrl { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("renderingMode")]
    public RenderingMode? RenderingMode { get; set; }
  }

  /// <summary>
  /// Specifies the options for the sitemap.xml file.
  /// </summary>
  public partial class Sitemap
  {
    /// <summary>
    /// Base URL for the website. It should start with http or https.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("baseUrl")]
    public Uri BaseUrl { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("changefreq")]
    public Changefreq? Changefreq { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fileOptions")]
    public Dictionary<string, FileOption> FileOptions { get; set; }

    /// <summary>
    /// The date of last modification of the page. If not specified, docfx sets the date to the
    /// build time.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("lastmod")]
    public string Lastmod { get; set; }

    /// <summary>
    /// the priority of this URL relative to other URLs on your site. Valid values range from 0.0
    /// to 1.0.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priority")]
    [JsonConverter(typeof(MinMaxValueCheckConverter))]
    public double? Priority { get; set; }
  }

  public partial class FileOption
  {
    /// <summary>
    /// Base URL for the website. It should start with http or https.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("baseUrl")]
    public Uri BaseUrl { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("changefreq")]
    public Changefreq? Changefreq { get; set; }

    /// <summary>
    /// The date of last modification of the page. If not specified, docfx sets the date to the
    /// build time.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("lastmod")]
    public string Lastmod { get; set; }

    /// <summary>
    /// the priority of this URL relative to other URLs on your site. Valid values range from 0.0
    /// to 1.0.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("priority")]
    [JsonConverter(typeof(MinMaxValueCheckConverter))]
    public double? Priority { get; set; }
  }

  public partial class MergeElement
  {
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("content")]
    public Content? Content { get; set; }

    /// <summary>
    /// Defines the output folder of the generated merge files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dest")]
    public string Dest { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fileMetadata")]
    public Dictionary<string, object> FileMetadata { get; set; }

    /// <summary>
    /// Contains metadata that will be applied to every file, in key-value pair format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("globalMetadata")]
    public Dictionary<string, object> GlobalMetadata { get; set; }

    /// <summary>
    /// Metadata that applies to toc files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("tocMetadata")]
    public Exclude? TocMetadata { get; set; }
  }

  public partial class MetadatumElement
  {
    /// <summary>
    /// When enabled, continues documentation generation in case of compilation errors.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("allowCompilationErrors")]
    public bool? AllowCompilationErrors { get; set; }

    /// <summary>
    /// Defines how categories in TOC are organized. This setting is valid when using `apiPage`
    /// or `markdown` output format. `mref` format don't support categories.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("categoryLayout")]
    public CategoryLayout? CategoryLayout { get; set; }

    /// <summary>
    /// Specify the base directory that is used to resolve code source.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("codeSourceBasePath")]
    public string CodeSourceBasePath { get; set; }

    /// <summary>
    /// (Deprecated) Defines the output folder of the generated metadata files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dest")]
    public string Dest { get; set; }

    /// <summary>
    /// Disables the default filter configuration file.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disableDefaultFilter")]
    public bool? DisableDefaultFilter { get; set; }

    /// <summary>
    /// Disables generation of view source links.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disableGitFeatures")]
    public bool? DisableGitFeatures { get; set; }

    /// <summary>
    /// Defines enum sort orders.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("enumSortOrder")]
    public EnumSortOrder? EnumSortOrder { get; set; }

    /// <summary>
    /// Defines the filter configuration file.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("filter")]
    public string Filter { get; set; }

    /// <summary>
    /// Specify the name to use for the global namespace.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("globalNamespaceId")]
    public string GlobalNamespaceId { get; set; }

    /// <summary>
    /// Include explicit interface implementations.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("includeExplicitInterfaceImplementations")]
    public bool? IncludeExplicitInterfaceImplementations { get; set; }

    /// <summary>
    /// Include private or internal APIs.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("includePrivateMembers")]
    public bool? IncludePrivateMembers { get; set; }

    /// <summary>
    /// Defines how member pages are organized.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("memberLayout")]
    public MemberLayout? MemberLayout { get; set; }

    /// <summary>
    /// Defines how namespaces in TOC are organized.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("namespaceLayout")]
    public NamespaceLayout? NamespaceLayout { get; set; }

    /// <summary>
    /// Do not run dotnet restore before building the projects.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("noRestore")]
    public bool? NoRestore { get; set; }

    /// <summary>
    /// Defines the output folder of the generated metadata files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("output")]
    public string Output { get; set; }

    /// <summary>
    /// Defines the output file format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("outputFormat")]
    public MetadatumOutputFormat? OutputFormat { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("properties")]
    public Dictionary<string, string> Properties { get; set; }

    /// <summary>
    /// Specify additinal assembly reference files.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("references")]
    public Content? References { get; set; }

    /// <summary>
    /// If set to true, DocFX would not render triple-slash-comments in source code as markdown.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("shouldSkipMarkup")]
    public bool? ShouldSkipMarkup { get; set; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("src")]
    public Content? Src { get; set; }

    /// <summary>
    /// When enabled, use CLR type names instead of language aliases.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("useClrTypeNames")]
    public bool? UseClrTypeNames { get; set; }
  }

  public enum PlantUmlOutputFormat { Ascii, AsciiUnicode, Eps, Html, LaTeX, Pdf, Png, Scxml, Svg, Vdx, Xmi };

  public enum RenderingMode { Local, Remote };

  /// <summary>
  /// Determines how frequently the page is likely to change. Valid values are always, hourly,
  /// daily, weekly, monthly, yearly, never.
  /// </summary>
  public enum Changefreq { Always, Daily, Hourly, Monthly, Never, Weekly, Yearly };

  /// <summary>
  /// Defines how categories in TOC are organized. This setting is valid when using `apiPage`
  /// or `markdown` output format. `mref` format don't support categories.
  /// </summary>
  public enum CategoryLayout { Flattened, Nested, None };

  /// <summary>
  /// Defines enum sort orders.
  /// </summary>
  public enum EnumSortOrder { Alphabetic, DeclaringOrder };

  /// <summary>
  /// Defines how member pages are organized.
  /// </summary>
  public enum MemberLayout { SamePage, SeparatePages };

  /// <summary>
  /// Defines how namespaces in TOC are organized.
  /// </summary>
  public enum NamespaceLayout { Flattened, Nested };

  /// <summary>
  /// Defines the output file format.
  /// </summary>
  public enum MetadatumOutputFormat { ApiPage, Markdown, Mref };

  public enum RuleValue { Diagnostic, Error, Info, Suggestion, Verbose, Warning };

  /// <summary>
  /// The file glob pattern collection for files that should be excluded, with path relative to
  /// property `src` is value is set.
  ///
  /// The file glob pattern collection, with path relative to property `src` is value is set.
  ///
  /// Specify a list of JSON file path containing fileMetadata settings.
  ///
  /// Specify a list of JSON file path containing globalMetadata settings.
  ///
  /// Specify PostProcessor array. Build-in HtmlProcessor is automatically added by default.
  ///
  /// The templates applied to each file in the documentation.
  ///
  /// The themes applied to the documentation.
  ///
  /// Specifies the urls of xrefmap used by content files. Supports local file path and
  /// HTTP/HTTPS urls.
  ///
  /// Metadata that applies to toc files.
  /// </summary>
  public partial struct Exclude
  {
    public string String;
    public string[] StringArray;

    public static implicit operator Exclude(string String) => new Exclude { String = String };
    public static implicit operator Exclude(string[] StringArray) => new Exclude { StringArray = StringArray };
  }

  public partial struct ContentElement
  {
    public DocF DocF;
    public string String;

    public static implicit operator ContentElement(DocF DocF) => new ContentElement { DocF = DocF };
    public static implicit operator ContentElement(string String) => new ContentElement { String = String };
  }

  /// <summary>
  /// Contains all the files to generate documentation, including metadata yml files and
  /// conceptual md files.
  ///
  /// Contains all the conceptual files which contains yaml header with uid and is intended to
  /// override the existing metadata yml files.
  ///
  /// Contains all the resource files that conceptual and metadata files dependent on, e.g.
  /// image files.
  ///
  /// Specify additinal assembly reference files.
  ///
  /// Defines the source projects to have metadata generated.
  /// </summary>
  public partial struct Content
  {
    public ContentElement[] AnythingArray;
    public DocF DocF;
    public string String;

    public static implicit operator Content(ContentElement[] AnythingArray) => new Content { AnythingArray = AnythingArray };
    public static implicit operator Content(DocF DocF) => new Content { DocF = DocF };
    public static implicit operator Content(string String) => new Content { String = String };
  }

  /// <summary>
  /// Markdig extension setting.
  /// </summary>
  public partial struct MarkdigExtensionElement
  {
    public MarkdigExtensionClass MarkdigExtensionClass;
    public string String;

    public static implicit operator MarkdigExtensionElement(MarkdigExtensionClass MarkdigExtensionClass) => new MarkdigExtensionElement { MarkdigExtensionClass = MarkdigExtensionClass };
    public static implicit operator MarkdigExtensionElement(string String) => new MarkdigExtensionElement { String = String };
  }

  public partial class DocFx
  {
    public static DocFx FromJson(string json) => JsonSerializer.Deserialize<DocFx>(json, DocFxHelper.Common.Converter.Settings);
  }

  public static class Serialize
  {
    public static string ToJson(this DocFx self) => JsonSerializer.Serialize(self, DocFxHelper.Common.Converter.Settings);
  }

  internal static class Converter
  {
    public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
    {
      Converters =
            {
                ContentConverter.Singleton,
                ContentElementConverter.Singleton,
                ExcludeConverter.Singleton,
                MarkdigExtensionElementConverter.Singleton,
                PlantUmlOutputFormatConverter.Singleton,
                RenderingModeConverter.Singleton,
                ChangefreqConverter.Singleton,
                CategoryLayoutConverter.Singleton,
                EnumSortOrderConverter.Singleton,
                MemberLayoutConverter.Singleton,
                NamespaceLayoutConverter.Singleton,
                MetadatumOutputFormatConverter.Singleton,
                RuleValueConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
    };
  }

  internal class ContentConverter : JsonConverter<Content>
  {
    public override bool CanConvert(Type t) => t == typeof(Content);

    public override Content Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      switch (reader.TokenType)
      {
        case JsonTokenType.String:
          var stringValue = reader.GetString();
          return new Content { String = stringValue };
        case JsonTokenType.StartObject:
          var objectValue = JsonSerializer.Deserialize<DocF>(ref reader, options);
          return new Content { DocF = objectValue };
        case JsonTokenType.StartArray:
          var arrayValue = JsonSerializer.Deserialize<ContentElement[]>(ref reader, options);
          return new Content { AnythingArray = arrayValue };
      }
      throw new Exception("Cannot unmarshal type Content");
    }

    public override void Write(Utf8JsonWriter writer, Content value, JsonSerializerOptions options)
    {
      if (value.String != null)
      {
        JsonSerializer.Serialize(writer, value.String, options);
        return;
      }
      if (value.AnythingArray != null)
      {
        JsonSerializer.Serialize(writer, value.AnythingArray, options);
        return;
      }
      if (value.DocF != null)
      {
        JsonSerializer.Serialize(writer, value.DocF, options);
        return;
      }
      throw new Exception("Cannot marshal type Content");
    }

    public static readonly ContentConverter Singleton = new ContentConverter();
  }

  internal class ContentElementConverter : JsonConverter<ContentElement>
  {
    public override bool CanConvert(Type t) => t == typeof(ContentElement);

    public override ContentElement Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      switch (reader.TokenType)
      {
        case JsonTokenType.String:
          var stringValue = reader.GetString();
          return new ContentElement { String = stringValue };
        case JsonTokenType.StartObject:
          var objectValue = JsonSerializer.Deserialize<DocF>(ref reader, options);
          return new ContentElement { DocF = objectValue };
      }
      throw new Exception("Cannot unmarshal type ContentElement");
    }

    public override void Write(Utf8JsonWriter writer, ContentElement value, JsonSerializerOptions options)
    {
      if (value.String != null)
      {
        JsonSerializer.Serialize(writer, value.String, options);
        return;
      }
      if (value.DocF != null)
      {
        JsonSerializer.Serialize(writer, value.DocF, options);
        return;
      }
      throw new Exception("Cannot marshal type ContentElement");
    }

    public static readonly ContentElementConverter Singleton = new ContentElementConverter();
  }

  internal class ExcludeConverter : JsonConverter<Exclude>
  {
    public override bool CanConvert(Type t) => t == typeof(Exclude);

    public override Exclude Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      switch (reader.TokenType)
      {
        case JsonTokenType.String:
          var stringValue = reader.GetString();
          return new Exclude { String = stringValue };
        case JsonTokenType.StartArray:
          var arrayValue = JsonSerializer.Deserialize<string[]>(ref reader, options);
          return new Exclude { StringArray = arrayValue };
      }
      throw new Exception("Cannot unmarshal type Exclude");
    }

    public override void Write(Utf8JsonWriter writer, Exclude value, JsonSerializerOptions options)
    {
      if (value.String != null)
      {
        JsonSerializer.Serialize(writer, value.String, options);
        return;
      }
      if (value.StringArray != null)
      {
        JsonSerializer.Serialize(writer, value.StringArray, options);
        return;
      }
      throw new Exception("Cannot marshal type Exclude");
    }

    public static readonly ExcludeConverter Singleton = new ExcludeConverter();
  }

  internal class MarkdigExtensionElementConverter : JsonConverter<MarkdigExtensionElement>
  {
    public override bool CanConvert(Type t) => t == typeof(MarkdigExtensionElement);

    public override MarkdigExtensionElement Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      switch (reader.TokenType)
      {
        case JsonTokenType.String:
          var stringValue = reader.GetString();
          return new MarkdigExtensionElement { String = stringValue };
        case JsonTokenType.StartObject:
          var objectValue = JsonSerializer.Deserialize<MarkdigExtensionClass>(ref reader, options);
          return new MarkdigExtensionElement { MarkdigExtensionClass = objectValue };
      }
      throw new Exception("Cannot unmarshal type MarkdigExtensionElement");
    }

    public override void Write(Utf8JsonWriter writer, MarkdigExtensionElement value, JsonSerializerOptions options)
    {
      if (value.String != null)
      {
        JsonSerializer.Serialize(writer, value.String, options);
        return;
      }
      if (value.MarkdigExtensionClass != null)
      {
        JsonSerializer.Serialize(writer, value.MarkdigExtensionClass, options);
        return;
      }
      throw new Exception("Cannot marshal type MarkdigExtensionElement");
    }

    public static readonly MarkdigExtensionElementConverter Singleton = new MarkdigExtensionElementConverter();
  }

  internal class PlantUmlOutputFormatConverter : JsonConverter<PlantUmlOutputFormat>
  {
    public override bool CanConvert(Type t) => t == typeof(PlantUmlOutputFormat);

    public override PlantUmlOutputFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "Ascii":
          return PlantUmlOutputFormat.Ascii;
        case "Ascii_Unicode":
          return PlantUmlOutputFormat.AsciiUnicode;
        case "Eps":
          return PlantUmlOutputFormat.Eps;
        case "Html":
          return PlantUmlOutputFormat.Html;
        case "LaTeX":
          return PlantUmlOutputFormat.LaTeX;
        case "Pdf":
          return PlantUmlOutputFormat.Pdf;
        case "Png":
          return PlantUmlOutputFormat.Png;
        case "Scxml":
          return PlantUmlOutputFormat.Scxml;
        case "Svg":
          return PlantUmlOutputFormat.Svg;
        case "Vdx":
          return PlantUmlOutputFormat.Vdx;
        case "Xmi":
          return PlantUmlOutputFormat.Xmi;
      }
      throw new Exception("Cannot unmarshal type PlantUmlOutputFormat");
    }

    public override void Write(Utf8JsonWriter writer, PlantUmlOutputFormat value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case PlantUmlOutputFormat.Ascii:
          JsonSerializer.Serialize(writer, "Ascii", options);
          return;
        case PlantUmlOutputFormat.AsciiUnicode:
          JsonSerializer.Serialize(writer, "Ascii_Unicode", options);
          return;
        case PlantUmlOutputFormat.Eps:
          JsonSerializer.Serialize(writer, "Eps", options);
          return;
        case PlantUmlOutputFormat.Html:
          JsonSerializer.Serialize(writer, "Html", options);
          return;
        case PlantUmlOutputFormat.LaTeX:
          JsonSerializer.Serialize(writer, "LaTeX", options);
          return;
        case PlantUmlOutputFormat.Pdf:
          JsonSerializer.Serialize(writer, "Pdf", options);
          return;
        case PlantUmlOutputFormat.Png:
          JsonSerializer.Serialize(writer, "Png", options);
          return;
        case PlantUmlOutputFormat.Scxml:
          JsonSerializer.Serialize(writer, "Scxml", options);
          return;
        case PlantUmlOutputFormat.Svg:
          JsonSerializer.Serialize(writer, "Svg", options);
          return;
        case PlantUmlOutputFormat.Vdx:
          JsonSerializer.Serialize(writer, "Vdx", options);
          return;
        case PlantUmlOutputFormat.Xmi:
          JsonSerializer.Serialize(writer, "Xmi", options);
          return;
      }
      throw new Exception("Cannot marshal type PlantUmlOutputFormat");
    }

    public static readonly PlantUmlOutputFormatConverter Singleton = new PlantUmlOutputFormatConverter();
  }

  internal class RenderingModeConverter : JsonConverter<RenderingMode>
  {
    public override bool CanConvert(Type t) => t == typeof(RenderingMode);

    public override RenderingMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "Local":
          return RenderingMode.Local;
        case "Remote":
          return RenderingMode.Remote;
      }
      throw new Exception("Cannot unmarshal type RenderingMode");
    }

    public override void Write(Utf8JsonWriter writer, RenderingMode value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case RenderingMode.Local:
          JsonSerializer.Serialize(writer, "Local", options);
          return;
        case RenderingMode.Remote:
          JsonSerializer.Serialize(writer, "Remote", options);
          return;
      }
      throw new Exception("Cannot marshal type RenderingMode");
    }

    public static readonly RenderingModeConverter Singleton = new RenderingModeConverter();
  }

  internal class ChangefreqConverter : JsonConverter<Changefreq>
  {
    public override bool CanConvert(Type t) => t == typeof(Changefreq);

    public override Changefreq Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "always":
          return Changefreq.Always;
        case "daily":
          return Changefreq.Daily;
        case "hourly":
          return Changefreq.Hourly;
        case "monthly":
          return Changefreq.Monthly;
        case "never":
          return Changefreq.Never;
        case "weekly":
          return Changefreq.Weekly;
        case "yearly":
          return Changefreq.Yearly;
      }
      throw new Exception("Cannot unmarshal type Changefreq");
    }

    public override void Write(Utf8JsonWriter writer, Changefreq value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case Changefreq.Always:
          JsonSerializer.Serialize(writer, "always", options);
          return;
        case Changefreq.Daily:
          JsonSerializer.Serialize(writer, "daily", options);
          return;
        case Changefreq.Hourly:
          JsonSerializer.Serialize(writer, "hourly", options);
          return;
        case Changefreq.Monthly:
          JsonSerializer.Serialize(writer, "monthly", options);
          return;
        case Changefreq.Never:
          JsonSerializer.Serialize(writer, "never", options);
          return;
        case Changefreq.Weekly:
          JsonSerializer.Serialize(writer, "weekly", options);
          return;
        case Changefreq.Yearly:
          JsonSerializer.Serialize(writer, "yearly", options);
          return;
      }
      throw new Exception("Cannot marshal type Changefreq");
    }

    public static readonly ChangefreqConverter Singleton = new ChangefreqConverter();
  }

  internal class MinMaxValueCheckConverter : JsonConverter<double>
  {
    public override bool CanConvert(Type t) => t == typeof(double);

    public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetDouble();
      if (value >= 0 && value <= 1)
      {
        return value;
      }
      throw new Exception("Cannot unmarshal type double");
    }

    public override void Write(Utf8JsonWriter writer, double value, JsonSerializerOptions options)
    {
      if (value >= 0 && value <= 1)
      {
        JsonSerializer.Serialize(writer, value, options);
        return;
      }
      throw new Exception("Cannot marshal type double");
    }

    public static readonly MinMaxValueCheckConverter Singleton = new MinMaxValueCheckConverter();
  }

  internal class CategoryLayoutConverter : JsonConverter<CategoryLayout>
  {
    public override bool CanConvert(Type t) => t == typeof(CategoryLayout);

    public override CategoryLayout Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "flattened":
          return CategoryLayout.Flattened;
        case "nested":
          return CategoryLayout.Nested;
        case "none":
          return CategoryLayout.None;
      }
      throw new Exception("Cannot unmarshal type CategoryLayout");
    }

    public override void Write(Utf8JsonWriter writer, CategoryLayout value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case CategoryLayout.Flattened:
          JsonSerializer.Serialize(writer, "flattened", options);
          return;
        case CategoryLayout.Nested:
          JsonSerializer.Serialize(writer, "nested", options);
          return;
        case CategoryLayout.None:
          JsonSerializer.Serialize(writer, "none", options);
          return;
      }
      throw new Exception("Cannot marshal type CategoryLayout");
    }

    public static readonly CategoryLayoutConverter Singleton = new CategoryLayoutConverter();
  }

  internal class EnumSortOrderConverter : JsonConverter<EnumSortOrder>
  {
    public override bool CanConvert(Type t) => t == typeof(EnumSortOrder);

    public override EnumSortOrder Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "alphabetic":
          return EnumSortOrder.Alphabetic;
        case "declaringOrder":
          return EnumSortOrder.DeclaringOrder;
      }
      throw new Exception("Cannot unmarshal type EnumSortOrder");
    }

    public override void Write(Utf8JsonWriter writer, EnumSortOrder value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case EnumSortOrder.Alphabetic:
          JsonSerializer.Serialize(writer, "alphabetic", options);
          return;
        case EnumSortOrder.DeclaringOrder:
          JsonSerializer.Serialize(writer, "declaringOrder", options);
          return;
      }
      throw new Exception("Cannot marshal type EnumSortOrder");
    }

    public static readonly EnumSortOrderConverter Singleton = new EnumSortOrderConverter();
  }

  internal class MemberLayoutConverter : JsonConverter<MemberLayout>
  {
    public override bool CanConvert(Type t) => t == typeof(MemberLayout);

    public override MemberLayout Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "samePage":
          return MemberLayout.SamePage;
        case "separatePages":
          return MemberLayout.SeparatePages;
      }
      throw new Exception("Cannot unmarshal type MemberLayout");
    }

    public override void Write(Utf8JsonWriter writer, MemberLayout value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case MemberLayout.SamePage:
          JsonSerializer.Serialize(writer, "samePage", options);
          return;
        case MemberLayout.SeparatePages:
          JsonSerializer.Serialize(writer, "separatePages", options);
          return;
      }
      throw new Exception("Cannot marshal type MemberLayout");
    }

    public static readonly MemberLayoutConverter Singleton = new MemberLayoutConverter();
  }

  internal class NamespaceLayoutConverter : JsonConverter<NamespaceLayout>
  {
    public override bool CanConvert(Type t) => t == typeof(NamespaceLayout);

    public override NamespaceLayout Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "flattened":
          return NamespaceLayout.Flattened;
        case "nested":
          return NamespaceLayout.Nested;
      }
      throw new Exception("Cannot unmarshal type NamespaceLayout");
    }

    public override void Write(Utf8JsonWriter writer, NamespaceLayout value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case NamespaceLayout.Flattened:
          JsonSerializer.Serialize(writer, "flattened", options);
          return;
        case NamespaceLayout.Nested:
          JsonSerializer.Serialize(writer, "nested", options);
          return;
      }
      throw new Exception("Cannot marshal type NamespaceLayout");
    }

    public static readonly NamespaceLayoutConverter Singleton = new NamespaceLayoutConverter();
  }

  internal class MetadatumOutputFormatConverter : JsonConverter<MetadatumOutputFormat>
  {
    public override bool CanConvert(Type t) => t == typeof(MetadatumOutputFormat);

    public override MetadatumOutputFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "apiPage":
          return MetadatumOutputFormat.ApiPage;
        case "markdown":
          return MetadatumOutputFormat.Markdown;
        case "mref":
          return MetadatumOutputFormat.Mref;
      }
      throw new Exception("Cannot unmarshal type MetadatumOutputFormat");
    }

    public override void Write(Utf8JsonWriter writer, MetadatumOutputFormat value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case MetadatumOutputFormat.ApiPage:
          JsonSerializer.Serialize(writer, "apiPage", options);
          return;
        case MetadatumOutputFormat.Markdown:
          JsonSerializer.Serialize(writer, "markdown", options);
          return;
        case MetadatumOutputFormat.Mref:
          JsonSerializer.Serialize(writer, "mref", options);
          return;
      }
      throw new Exception("Cannot marshal type MetadatumOutputFormat");
    }

    public static readonly MetadatumOutputFormatConverter Singleton = new MetadatumOutputFormatConverter();
  }

  internal class RuleValueConverter : JsonConverter<RuleValue>
  {
    public override bool CanConvert(Type t) => t == typeof(RuleValue);

    public override RuleValue Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      switch (value)
      {
        case "diagnostic":
          return RuleValue.Diagnostic;
        case "error":
          return RuleValue.Error;
        case "info":
          return RuleValue.Info;
        case "suggestion":
          return RuleValue.Suggestion;
        case "verbose":
          return RuleValue.Verbose;
        case "warning":
          return RuleValue.Warning;
      }
      throw new Exception("Cannot unmarshal type RuleValue");
    }

    public override void Write(Utf8JsonWriter writer, RuleValue value, JsonSerializerOptions options)
    {
      switch (value)
      {
        case RuleValue.Diagnostic:
          JsonSerializer.Serialize(writer, "diagnostic", options);
          return;
        case RuleValue.Error:
          JsonSerializer.Serialize(writer, "error", options);
          return;
        case RuleValue.Info:
          JsonSerializer.Serialize(writer, "info", options);
          return;
        case RuleValue.Suggestion:
          JsonSerializer.Serialize(writer, "suggestion", options);
          return;
        case RuleValue.Verbose:
          JsonSerializer.Serialize(writer, "verbose", options);
          return;
        case RuleValue.Warning:
          JsonSerializer.Serialize(writer, "warning", options);
          return;
      }
      throw new Exception("Cannot marshal type RuleValue");
    }

    public static readonly RuleValueConverter Singleton = new RuleValueConverter();
  }

  public class DateOnlyConverter : JsonConverter<DateOnly>
  {
    private readonly string serializationFormat;
    public DateOnlyConverter() : this(null) { }

    public DateOnlyConverter(string? serializationFormat)
    {
      this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
    }

    public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      return DateOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
  }

  public class TimeOnlyConverter : JsonConverter<TimeOnly>
  {
    private readonly string serializationFormat;

    public TimeOnlyConverter() : this(null) { }

    public TimeOnlyConverter(string? serializationFormat)
    {
      this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
    }

    public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      var value = reader.GetString();
      return TimeOnly.Parse(value!);
    }

    public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
            => writer.WriteStringValue(value.ToString(serializationFormat));
  }

  internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
  {
    public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

    private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

    private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
    private string? _dateTimeFormat;
    private CultureInfo? _culture;

    public DateTimeStyles DateTimeStyles
    {
      get => _dateTimeStyles;
      set => _dateTimeStyles = value;
    }

    public string? DateTimeFormat
    {
      get => _dateTimeFormat ?? string.Empty;
      set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
    }

    public CultureInfo Culture
    {
      get => _culture ?? CultureInfo.CurrentCulture;
      set => _culture = value;
    }

    public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
    {
      string text;


      if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
              || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
      {
        value = value.ToUniversalTime();
      }

      text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

      writer.WriteStringValue(text);
    }

    public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
      string? dateText = reader.GetString();

      if (string.IsNullOrEmpty(dateText) == false)
      {
        if (!string.IsNullOrEmpty(_dateTimeFormat))
        {
          return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
        }
        else
        {
          return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
        }
      }
      else
      {
        return default(DateTimeOffset);
      }
    }


    public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
  }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
